MovieCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from apps.account.views import SiteLoginView, SiteSignupView
from django.conf.urls import handler404, url
from django.views.static import serve


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("movie/", include("apps.movie.urls")),
    path("cart/", include("apps.cart.urls")),
    path("checkout/", include("apps.checkout.urls")),
    # user authenticated
    path("account/", include("django.contrib.auth.urls")),
    path("account/", include("apps.account.urls")),
    path("login/", SiteLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SiteSignupView.as_view(), name="signup"),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    try:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns
    except ImportError:
        pass

handler404 = "apps.core.views.error404"

apps/checkout/urls.py
from django.urls import path
from django.conf.urls import url
from apps.checkout.views import CheckoutView, CheckoutDoneView, checkout

app_name = "checkout"

urlpatterns = [
    path("", CheckoutView, name="checkout"),
    path("payment/", checkout, name="payment"),
    path("done/", CheckoutDoneView.as_view(), name="checkout-done"),
]

apps/core/urls.py
from django.urls import path
from .views import AboutView, ContactView, HomeListView

app_name = "core"

urlpatterns = [
    path("", HomeListView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
]

apps/movie/urls.py
from django.urls import path
from .views import MovieDetailView, MovieListView, SearchMovie
from .models import Movie

app_name = "movie"

urlpatterns = [
    path("all/", MovieListView.as_view(model=Movie), name="movie-list"),
    path("<slug:the_slug>", MovieDetailView.as_view(), name="movie-detail"),
    path("search/", SearchMovie.as_view(), name="search-movie"),
]

apps/checkout/models.py
from django.db import models
from apps.account.models import CustomerUser
from apps.cart.models import Cart
from django.utils import timezone


class Order(models.Model):
    user_id = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    cart_id = models.ForeignKey(Cart, on_delete=models.CASCADE)
    fullname = models.CharField(default="", max_length=100, null=True)
    shipping_address = models.CharField(default="", max_length=255)
    phone_number = models.IntegerField(null=True)
    order_description = models.CharField(default="", max_length=255)
    order_total = models.DecimalField(max_digits=9, decimal_places=2)
    is_complete = models.BooleanField(default=False)
    create_date = models.DateTimeField(default=timezone.now, editable=False)
    update_date = models.DateTimeField(default=timezone.now)

    def save(self, *args, **kwargs):
        """ On save, update timestamps """
        if not self.id:
            self.create = timezone.now()
        self.update_date = timezone.now()
        return super(Order, self).save(*args, **kwargs)

apps/checkout/forms.py
from django import forms
from apps.checkout.models import Order
import re


class CheckoutForm(forms.ModelForm):
    order_description = forms.CharField(widget=forms.Textarea, required=False)

    class Meta:
        model = Order
        fields = ("fullname", "shipping_address", "phone_number", "order_description")

    def clean_fullname(self):
        fullname = self.cleaned_data['fullname']

        string_is_valid = check_symbol(fullname)

        if string_is_valid:
            return fullname
        else:
            raise forms.ValidationError("Letters and numbers only. Please try again without symbols.")

    def clean_shipping_address(self):
        shipping_address = self.cleaned_data['shipping_address']

        string_is_valid = check_symbol(shipping_address)

        if string_is_valid:
            return shipping_address
        else:
            raise forms.ValidationError("Letters and numbers only. Please try again without symbols.")

    def clean_order_description(self):
        order_description = self.cleaned_data['order_description']
        string_is_valid = check_symbol(order_description)

        if string_is_valid:
            return order_description
        else:
            raise forms.ValidationError("Letters and numbers only. Please try again without symbols.")


def check_symbol(string):
    regex = re.compile('[@_!#$%^&*()<>?/\|}{~:]')

    if(regex.search(string) == None):
        return True
    else:
        return False

apps/checkout/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import View, TemplateView
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from apps.checkout.forms import CheckoutForm
from apps.cart.models import Cart
from apps.checkout.models import Order
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy


@login_required
def CheckoutView(request):
    try:
        # kiem tra xem use hien tai co order nao hay khong
        order_of_user = Order.objects.get(
            user_id=request.user, is_complete=False
        )
        # Neu nhu nguoi dung da co
        # Cap nhat la gia tien cua order
        cart_of_user = Cart.objects.filter(
            user_id=request.user, is_active=True
        )[0]
        order_of_user.order_total = float(cart_of_user.get_total())
        order_of_user.save()

        form = CheckoutForm()

        context = {"form": form, "cart": cart_of_user}
        return render(request, "checkout/checkout.html", context)

    except ObjectDoesNotExist:
        # neu nguoi dung chua co se tao moi 1 order
        cart_of_user = Cart.objects.filter(
            user_id=request.user, is_active=True
        )
        if cart_of_user.exists():  # kiem tra nguoi dung co gio hang nao khong
            cart = cart_of_user[0]
            new_order = Order.objects.create(
                user_id=request.user,
                cart_id=cart,
                order_total=int(cart.get_total()),
            )
            return redirect("checkout:checkout")


@login_required
def checkout(request):
    form = CheckoutForm(request.POST, request.FILES)
    order = Order.objects.get(user_id=request.user, is_complete=False)
    cart_of_user = Cart.objects.filter(
        user_id=request.user, is_active=True
    )[0]
    if form.is_valid():
        if order.cart_id == cart_of_user:
            fullname = form.cleaned_data.get("fullname")
            shipping_address = form.cleaned_data.get("shipping_address")
            phone_number = form.cleaned_data.get("phone_number")
            order_description = form.cleaned_data.get("order_description")

            # save form
            order.fullname = fullname
            order.shipping_address = shipping_address
            order.phone_number = phone_number
            order.order_description = order_description
            order.is_complete = True
            order.save()

            # change status cart and cart_movie
            cart_of_user.is_active = False
            cart_of_user.save()

            for cart_movie in cart_of_user.movies.all():
                cart_movie.is_active = False
                cart_movie.save()

            # send email success payment
            messages = render_to_string("checkout/checkout_email.html", {
                'name': order.user_id.username,
            })
            email = EmailMessage(
                "Thank you for purchasing movies",
                messages,
                settings.DEFAULT_FROM_EMAIL,
                [request.user.email],
            )
            email.fail_silently = False
            email.send()
            # payment success
            return HttpResponseRedirect(reverse_lazy('checkout:checkout-done'))
    else:
        context = {"form": form, "cart": cart_of_user}
        return render(request, "checkout/checkout.html", context)


class CheckoutDoneView(LoginRequiredMixin, TemplateView):
    template_name = "checkout/checkout_done.html"

apps/templates/checkout/checkout.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Check Out | Movie Center
{% endblock title %}

{% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}"/>
{% endblock cssblock %} {% block content %}

    <section class="section1 relative text-center">
        <div class="jumbotron text-center">
            <h1 class="separator"><small>SHOP</small></h1>
            <span class="font-weight-bold">CHECK OUT</span>
        </div>
    </section>

    <section class="section2">
        <nav aria-label="breadcrumb" class="bg-light section-xl">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a class="mau" href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Checkout</li>
            </ol>
        </nav>
    </section>

    <div class="container">
        <br>
        <h3><strong>YOUR CHOICES</strong></h3>
        <br>
        <table class="table table-hover text-left">
            <thead class="bg-danger">
            <tr class="bg-accent">
                <th class="text-light">Movie</th>
                <th></th>
                <th></th>
                <th class="text-light">Price</th>
            </tr>
            </thead>
            {% for cart_movie in cart.movies.all %}
                <tr>
                    <td class="text-dark">
                        <a href="{% url 'movie:movie-detail' cart_movie.movie.slug %}" class="text-body">
                            {{ cart_movie.movie.title }}
                        </a>
                    </td>
                    <td></td>
                    <td></td>
                    <td class="text-body">
                        {{ cart_movie.movie.price }} $
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td><strong>Total</strong></td>
                <td></td>
                <td></td>
                <td><strong>{{ cart.get_total }} $</strong></td>
            </tr>
            <tr></tr>
        </table>
    </div>

    <div class="row">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">
                    <form class="rd-mailform text-left" method="post" action="{% url 'checkout:payment' %}">
                        {% csrf_token %}
                        {{ form | crispy }}
                        {% if redirect_field_value %}
                            <input type="hidden" name="{{ redirect_field_name }}"
                                   value="{{ redirect_field_value }}"/>
                        {% endif %}
                        <div class="text-center">
                            <button class="btn btn-danger btn-lg btn-block" type="submit">PAYMENT</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/templates/checkout/checkout_done.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    Sign Up | Movie Center
{% endblock title %}

{% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
{% endblock cssblock %}

{% block content %}

<section class="relative">
    <div class="container">
        <div class="jumbotron text-center">
            <h1 class="separator"><small>Update</small></h1>
            <span class="font-weight-bold">Update your profile</span>
        </div>
    </div>
</section>

<nav aria-label="breadcrumb" class="bg-light section-xl">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a class="mau" href="#">Home</a></li>
        <li class="breadcrumb-item"><a class="mau" href="#">{{ user.username }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Update Profile</li>
    </ol>
</nav>

<div class="row">
  <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
          <div class="card-body">
            <p>
              <h1>Payment success!</h1>
              <a class="btn btn-danger" href="{% url 'core:home' %}">Return Home</a>
            </p>
          </div>
      </div>
  </div>
</div>

{% endblock content %}

apps/templates/checkout/checkout_email.html
{% autoescape off %}
Thanks {{ name }} so much,

Just wanted to thank you for purchasing movies in my website.
Hope you enjoy with all movies you choiced.

Sincerely,
TheMovieCenter Team.
{% endautoescape %}