MovieCenter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from apps.account.views import SiteLoginView, SiteSignupView
from django.conf.urls import handler404, url
from django.views.static import serve


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("movie/", include("apps.movie.urls")),
    path("cart/", include("apps.cart.urls")),
    path("checkout/", include("apps.checkout.urls")),
    # user authenticated
    path("account/", include("django.contrib.auth.urls")),
    path("account/", include("apps.account.urls")),
    path("login/", SiteLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SiteSignupView.as_view(), name="signup"),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    try:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls)),] + urlpatterns
    except ImportError:
        pass

handler404 = "apps.core.views.error404"

apps/cart/urls.py
from django.urls import path
from .views import CartDetailView, add_to_cart, remove_from_cart

app_name = "cart"

urlpatterns = [
    path("", CartDetailView.as_view(), name="cart"),
    path("add/<slug>/", add_to_cart, name="add-to-cart"),
    path("remove/<slug>/", remove_from_cart, name="remove-from-cart"),
]

apps/checkout/urls.py
from django.urls import path
from django.conf.urls import url
from apps.checkout.views import CheckoutView, CheckoutDoneView, checkout

app_name = "checkout"

urlpatterns = [
    path("", CheckoutView, name="checkout"),
    path("payment/", checkout, name="payment"),
    path("done/", CheckoutDoneView.as_view(), name="checkout-done"),
]

apps/movie/urls.py
from django.urls import path
from .views import MovieDetailView, MovieListView, SearchMovie
from .models import Movie

app_name = "movie"

urlpatterns = [
    path("all/", MovieListView.as_view(model=Movie), name="movie-list"),
    path("<slug:the_slug>", MovieDetailView.as_view(), name="movie-detail"),
    path("search/", SearchMovie.as_view(), name="search-movie"),
]

apps/cart/models.py
from django.db import models
from apps.movie.models import Movie
from apps.account.models import CustomerUser
import datetime
from django.utils import timezone


class CartMovie(models.Model):
    user_id = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def get_movie_price(self):
        return self.movie.price


class Cart(models.Model):
    user_id = models.ForeignKey(CustomerUser, on_delete=models.CASCADE)
    movies = models.ManyToManyField(CartMovie)
    create_date = models.DateTimeField(default=timezone.now, editable=False)
    update_date = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)

    def get_total(self):
        total = 0
        for movie in self.movies.all():
            total += movie.get_movie_price()
        return total

    def save(self, *args, **kwargs):
        """ On save, update timestamps """
        if not self.id:
            self.created = timezone.now()
        self.update_date = timezone.now()
        return super(Cart, self).save(*args, **kwargs)

apps/cart/views.py
from django.views.generic import View
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from apps.movie.models import Movie
from apps.cart.models import Cart, CartMovie
from datetime import datetime
from django.http.response import HttpResponseRedirect
from django.utils import timezone
from django.http import HttpResponseRedirect


class CartDetailView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            cart = Cart.objects.get(user_id=self.request.user, is_active=True)
            context = {"cart": cart}
            return render(self.request, "cart/cart.html", context)
        except ObjectDoesNotExist:
            cart = Cart.objects.create(user_id=self.request.user, is_active=True)
            return HttpResponseRedirect("/cart")


@login_required
def add_to_cart(request, slug):
    # the movie has just been added by user
    movie = get_object_or_404(Movie, slug=slug)
    cart_movie, created = CartMovie.objects.get_or_create(
        movie=movie, user_id=request.user, is_active=True
    )
    cart_of_user = Cart.objects.filter(user_id=request.user, is_active=True)

    # check current cart of user
    if cart_of_user.exists():
        cart = cart_of_user[0]
        # check the movie that has been added to the shopping cart by the user
        if cart.movies.filter(movie__slug=movie.slug).exists():
            return redirect("cart:cart")
        else:
            cart.movies.add(cart_movie)
            cart.save()
            return redirect("cart:cart")
    else:
        # user current have no cart, we'll create a new cart.
        create_date = datetime.now()
        cart = Cart.objects.create(user_id=request.user, create_date=create_date)
        cart.movies.add(cart_movie)
        return redirect("cart:cart")


@login_required
def remove_from_cart(request, slug):
    movie = get_object_or_404(Movie, slug=slug)
    cart_of_usert = Cart.objects.filter(user_id=request.user, is_active=True)

    if cart_of_usert.exists():
        cart = cart_of_usert[0]
        # check if the order item is in the order
        if cart.movies.filter(movie__slug=movie.slug).exists():
            cart_movie = CartMovie.objects.filter(
                movie=movie, user_id=request.user, is_active=True
            )[0]
            cart.movies.remove(cart_movie)
            cart.save()
            cart_movie.delete()
            return redirect("cart:cart")
        else:
            return redirect("movie:movie-list", slug=slug)
    else:
        return redirect("movie:movie-list", slug=slug)

apps/templates/cart/cart.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Your cart | Movie Center
{% endblock title %}

{% block cssblock %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock cssblock %}

{% block content %}
    <section class="relative text-center">
        <div class="container">
            <div class="jumbotron text-center">
                <h1 class="separator">CHOOSE YOUR FAVORITE MOVIES</h1>
                <span class="font-weight-bold">SHOPPING CART</span>
            </div>
        </div>
    </section>
    </head>

    <body>
    <nav aria-label="breadcrumb" class="bg-light section-xl">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a class="mau" href="#">Home</a></li>
            <li class="breadcrumb-item"><a class="mau" href="#">Shop</a></li>
            <li class="breadcrumb-item active" aria-current="page">
                Shopping Cart
            </li>
        </ol>
    </nav>

    <!-- Page-->
    <div class="page text-center animated" style="animation-duration: 500ms;">
        <main class="page-content">
            <section class="section section-inset-1">
                <div class="container">
                    <div class="row row-45 justify-content-end">
                        <div class="col-12 section-inset-1">
                            <div class="table-responsive">
                                <table class="table table-hover text-left">
                                    <thead>
                                    <tr class="bg-accent">
                                        <th></th>
                                        <th>Product</th>
                                        <th>Price</th>
                                    </tr>
                                    </thead>

                                    {% for cart_movie in cart.movies.all %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'cart:remove-from-cart' cart_movie.movie.slug %}"><span
                                                        class="icon icon-xs fa-trash icon-gray"></span></a>
                                            </td>
                                            <td>
                                                <a href="{% url 'movie:movie-detail' cart_movie.movie.slug %}" class="text-dark">
                                                    {{ cart_movie.movie.title }}
                                                </a>
                                            </td>
                                            <td>{{ cart_movie.movie.price }}$</td>
                                        </tr>
                                    {% empty %}
                                        <tr>
                                            <td>Your cart is empty</td>
                                        </tr>
                                    {% endfor %}

                                    {% if cart.get_total %}
                                        </tbody>
                                        </table>
                                        </div>
                                        <div class="card-footer">
                                            <div class="coupon col-md-5 col-sm-5 no-padding-left pull-left">
                                                <div class="row">
                                                    <div class="pull-right" style="margin: 10px">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        </div>
                                        <div class="col-12 col-md-7 col-md-offset-5 col-xl-4 col-xl-offset-8">
                                        <div class="table-responsive">
                                        <table class="table table-hover text-left">
                                        <thead>
                                        <tr class="bg-accent">
                                            <th>Cart Totals</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td class="text-gray">Total</td>
                                            <td class="fw-b">{{ cart.get_total }}$</td>
                                        </tr>
                                    {% endif %}
                                    </tbody>
                                    </table>
                                    </div>
                                    {% if cart.get_total %}
                                        <a class="btn btn-danger btn-sm btn-min-width-lg offset-custom-5"
                                           href="{% url 'checkout:checkout' %}">proceed to
                                            checkout</a>
                                    {% else %}
                                        <a class="btn btn-danger btn-sm btn-min-width-lg offset-custom-5"
                                           href="/movie/all/">Continue Shopping</a>
                                    {% endif %}
                                    </td>
                                    </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Page Footer-->
    </div>
    <!-- Global Mailform Output-->
{% endblock content %}